### ISSUE TITLE
Link to sample spreadsheet is 'access denied'

### ISSUE THREAD

**Issue by mhawksey** [ttsukagoshi/website-monitoring-by-gas#51]
Hi,

This looks like a great solution! An issue I encountered is that the Google Sheet included in "[Copy this sample spreadsheet to your Google Drive](https://github.com/ttsukagoshi/website-monitoring-by-gas/blame/main/README.md#L13)" is access denied. Not sure if this is by design to monitor usage or incorrect sharing settings. Would be good to fix the link or explain the access process. 

Thanks for sharing this!
Martin

**Comment by ttsukagoshi** [comment]
Hi @mhawksey and thank you for the heads-up!👍 The `access denied` was a mistake left out in the sharing settings; I simply wanted everyone to be viewers so they can copy the file whenever they one to. This has now been fixed, and I'll follow up with adding a few more lines to the documentation later on😃

**Comment by mhawksey** [comment]
@ttsukagoshi thanks for the clarification and fix - a little tip, you can avoid File > Make copy by replacing /edit with /copy in the url e.g. https://docs.google.com/spreadsheets/d/1JvO090VcgvF-WwciNnzRb1_nonKJC5QHN73h_CXS1Cw/copy

**Comment by ttsukagoshi** [comment]
👀 That makes a huge difference! Thank you again for your comment; I've changed the URL of the sample spreadsheet from `~/edit`to `~/copy` in #53
